-- vim.cmd [[set termguicolors]]
-- vim.cmd [[let g:gruvbox_contrast_dark='hard']]
-- vim.cmd [[let g:gruvbox_contrast_light='hard']]
-- vim.cmd [[colorscheme gruvbox]]
-- vim.cmd [[hi LspCxxHlGroupMemberVariable guifg=#83a598]]
vim.cmd [[colorscheme default]]
